// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Мониторинг_и_прогнозирование_пробок.Data;

#nullable disable

namespace Мониторинг_и_прогнозирование_пробок.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20260605122131_AddUsers")]
    partial class AddUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Мониторинг_и_прогнозирование_пробок.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Мониторинг_и_прогнозирование_пробок.Models.Историческая_скорость", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataVremya")
                        .HasColumnType("datetime2");

                    b.Property<int>("IDPrognoza")
                        .HasColumnType("int");

                    b.Property<decimal>("ScorostBystrPotoka")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ScorostMedlPotoka")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SrScorost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Прогноз_скоростиID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Прогноз_скоростиID");

                    b.ToTable("HistorySpeeds");
                });

            modelBuilder.Entity("Мониторинг_и_прогнозирование_пробок.Models.Прогноз_скорости", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataSozdaniaPrognoza")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrognozSpeed")
                        .HasColumnType("int");

                    b.Property<DateTime>("PrognozaDataVremya")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("PrognozSpeeds");
                });

            modelBuilder.Entity("Мониторинг_и_прогнозирование_пробок.Models.Тип_дня", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<int>("IDPrognoz")
                        .HasColumnType("int");

                    b.Property<int>("Nagruzki")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("prazdnik")
                        .HasColumnType("bit");

                    b.Property<int?>("Прогноз_СкоростиID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Прогноз_СкоростиID");

                    b.ToTable("TypeDays");
                });

            modelBuilder.Entity("Мониторинг_и_прогнозирование_пробок.Models.Историческая_скорость", b =>
                {
                    b.HasOne("Мониторинг_и_прогнозирование_пробок.Models.Прогноз_скорости", "Прогноз_скорости")
                        .WithMany()
                        .HasForeignKey("Прогноз_скоростиID");

                    b.Navigation("Прогноз_скорости");
                });

            modelBuilder.Entity("Мониторинг_и_прогнозирование_пробок.Models.Тип_дня", b =>
                {
                    b.HasOne("Мониторинг_и_прогнозирование_пробок.Models.Прогноз_скорости", "Прогноз_Скорости")
                        .WithMany()
                        .HasForeignKey("Прогноз_СкоростиID");

                    b.Navigation("Прогноз_Скорости");
                });
#pragma warning restore 612, 618
        }
    }
}
